export const questions = [
  {
    question: "What is your favourite colour?",
    choices: ["Blue", "Green", "Yellow", "Black", "Red"],
    titles: [
      "House of Roc",
      "House of Dragon",
      "House of Garuda",
      "House of Tulpar",
      "House of Phoenix",
    ],
    images: [
      "ROC.png",
      "DRAGON.png",
      "GARUDA.png",
      "TULPAR.png",
      "PHOENIX.png",
    ],
    links: [
      [{ label: "Explore Roc Here", url: "#" }],
      [{ label: "Explore Dragon Here", url: "#" }],
      [{ label: "Explore Garuda Here", url: "#" }],
      [{ label: "Explore Tulpar Here", url: "#" }],
      [{ label: "Explore Phoenix Here", url: "#" }],
    ],
  },
  {
    question: "What do you like to do during your free time?",
    choices: [
      "Playing sports with my friends!",
      "Arts and Craft",
      "Dancing",
      "Enjoying music",
      "Cooking and Baking",
      "Explore a different activity!",
    ],
    titles: [
      "Sporty ⚽️",
      "Creative 💡️",
      "Creative 💡️",
      "Creative 💡️",
      "Creative 💡️",
      "Curious 👀️",
    ],
    images: [
      "sports.jpg",
      "clubsocs.JPG",
      "clubsocs.JPG",
      "clubsocs.JPG",
      "clubsocs.JPG",
      "curious.JPG",
    ],
    links: [
      [{ label: "CAPT Sports", url: "#" }, { label: "Sports Committee", url: "#" }],
      [{ label: "Clubs & Societies", url: "#" }, { label: "Clubs & Societies Committee", url: "#" }],
      [{ label: "Clubs & Societies", url: "#" }, { label: "Clubs & Societies Committee", url: "#" }],
      [{ label: "Clubs & Societies", url: "#" }, { label: "Clubs & Societies Committee", url: "#" }],
      [{ label: "Clubs & Societies", url: "#" }, { label: "Clubs & Societies Committee", url: "#" }],
      [{ label: "CAPT Sports", url: "#" }, { label: "Clubs & Societies", url: "#"}],
    ],
  },
  {
    question:
      "Imagine you are at the library, pick the book title that interests you most!",
    choices: [
      "Pursuit of Happiness",
      "Bioethics in the 21st Century",
      "Beyond Borders: Migrants",
      "Inside the Museum",
    ],
    titles: ["", "", "", ""],
    images: ["happiness.jpg", "bioethics.jpg", "migrants.jpg", "museums.jpg"],
    links: [
      [{ label: "Pursuit of Happiness", url: "#" }, { label: "Other Junior Seminars", url: "#" }],
      [{ label: "Bioethics in the 21st Century", url: "#" }, { label: "Other Junior Seminars", url: "#" }],
      [{ label: "Beyond the Borders: Migrants", url: "#" }, { label: "Other Junior Seminars", url: "#" }],
      [{ label: "Inside The Museum", url: "#" }, { label: "Other Junior Seminars", url: "#" }],
    ],
  },
  {
    question: "Pick a community you want to engage with!",
    choices: [
      "Deaf Community",
      "Underprivileged Elderly",
      "Foster Children",
      "Animals",
      "Migrants",
      "Explore a different community!",
    ],
    titles: [
      "Deaf Community",
      "Underprivileged Elderly",
      "Foster Children",
      "Animals",
      "Migrants",
      "Explore a different community!",
    ],
    images: [
      "Deaf Community",
      "Underprivileged Elderly",
      "Foster Children",
      "Animals",
      "Migrants",
      "Explore a different community!",
    ],
    links: [
      [{ label: "CAPT in Silence", url: "#" }, { label: "Other CE Projects", url: "#" }],
      [{ label: "ACE Elderly", url: "#" }, { label: "Other CE Projects", url: "#" }],
      [{ label: "CAPT Kindle", url: "#" }, { label: "Other CE Projects", url: "#" }],
      [{ label: "pACE", url: "#" }, { label: "Other CE Projects", url: "#" }],
      [{ label: "Social Innovation", url: "#" }, { label: "Other CE Projects", url: "#" }],
    ],
  },
];
