export const questions = [
  {
    question: "What is your favourite colour?",
    choices: ["Blue", "Green", "Yellow", "Black", "Red"],
    titles: [
      "House of Roc",
      "House of Dragon",
      "House of Garuda",
      "House of Tulpar",
      "House of Phoenix",
    ],
    images: [
      "ROC.png",
      "DRAGON.png",
      "GARUDA.png",
      "TULPAR.png",
      "PHOENIX.png",
    ],
    links: [
      [{ label: "Explore Roc Here", url: "https://captlife.com/roc-neighbourhood-page/" }],
      [{ label: "Explore Dragon Here", url: "https://captlife.com/dragon-neighbourhood-page/" }],
      [{ label: "Explore Garuda Here", url: "https://captlife.com/garuda-neighbourhood-page/" }],
      [{ label: "Explore Tulpar Here", url: "https://captlife.com/tulpar-neighbourhood-page/" }],
      [{ label: "Explore Phoenix Here", url: "https://captlife.com/phoenix-neighbourhood-page/" }],
    ],
  },
  {
    question: "What do you like to do during your free time?",
    choices: [
      "Playing sports with my friends!",
      "Arts and Craft",
      "Dancing",
      "Enjoying music",
      "Cooking and Baking",
      "Explore a different activity!",
    ],
    titles: [
      "Sporty ⚽️",
      "Creative 💡️",
      "Creative 💡️",
      "Creative 💡️",
      "Creative 💡️",
      "Curious 👀️",
    ],
    images: [
      "sports.jpg",
      "clubsocs.JPG",
      "clubsocs.JPG",
      "clubsocs.JPG",
      "clubsocs.JPG",
      "curious.JPG",
    ],
    links: [
      [{ label: "CAPT Sports", url: "https://captlife.com/life/sports/" }, { label: "Sports Committee", url: "https://captlife.com/csc/sports/" }],
      [{ label: "Clubs & Societies", url: "https://captlife.com/csc/clubsocs/" }, { label: "Clubs & Societies Committee", url: "https://captlife.com/life/clubs-and-societies/CSC" }],
      [{ label: "Clubs & Societies", url: "https://captlife.com/csc/clubsocs/" }, { label: "Clubs & Societies Committee", url: "https://captlife.com/life/clubs-and-societies/CSC" }],
      [{ label: "Clubs & Societies", url: "https://captlife.com/csc/clubsocs/" }, { label: "Clubs & Societies Committee", url: "https://captlife.com/life/clubs-and-societies/CSC" }],
      [{ label: "Clubs & Societies", url: "https://captlife.com/csc/clubsocs/" }, { label: "Clubs & Societies Committee", url: "https://captlife.com/life/clubs-and-societies/CSC" }],
      [{ label: "CAPT Sports", url: "https://captlife.com/life/sports/" }, { label: "Clubs & Societies", url: "https://captlife.com/csc/clubsocs/"}],
    ],
  },
  {
    question:
      "Imagine you are at the library, pick the book title that interests you most!",
    choices: [
      "Pursuit of Happiness",
      "Bioethics in the 21st Century",
      "Beyond Borders: Migrants",
      "Inside the Museum",
    ],
    titles: ["", "", "", ""],
    images: ["happiness.jpg", "bioethics.jpg", "migrants.jpg", "museums.jpg"],
    links: [
      [{ label: "Pursuit of Happiness", url: "https://captlife.com/captmods/utc1409" }, { label: "Other Junior Seminars", url: "https://captlife.com/captmods/" }],
      [{ label: "Bioethics in the 21st Century", url: "https://captlife.com/captmods/utc1417/" }, { label: "Other Junior Seminars", url: "https://captlife.com/captmods/" }],
      [{ label: "Beyond the Borders: Migrants", url: "https://captlife.com/captmods/utc1420" }, { label: "Other Junior Seminars", url: "https://captlife.com/captmods/" }],
      [{ label: "Inside The Museum", url: "https://captlife.com/captmods/utc1419" }, { label: "Other Junior Seminars", url: "https://captlife.com/captmods/" }],
    ],
  },
  {
    question: "Pick a community you want to engage with!",
    choices: [
      "Deaf Community",
      "Underprivileged Elderly",
      "Foster Children",
      "Animals",
      "Migrants",
      "Explore a different community!",
    ],
    titles: [
      "",
      "",
      "",
      "",
      "",
      "",
    ],
    images: [
      "deaf.jpg",
      "blank.jpg",
      "blank.jpg",
      "blank.jpg",
      "migrants.jpg",
      "si.JPG",
    ],
    links: [
      [{ label: "CAPT in Silence", url: "https://www.instagram.com/captinsilence/" }, { label: "Other CE Projects", url: "https://captlife.com/life/ace-projects/" }],
      [{ label: "ACE Elderly", url: "https://www.instagram.com/capt.elderly/" }, { label: "Other CE Projects", url: "https://captlife.com/life/ace-projects/" }],
      [{ label: "CAPT Kindle", url: "https://www.instagram.com/capt.kindle/" }, { label: "Other CE Projects", url: "https://captlife.com/life/ace-projects/" }],
      [{ label: "pACE", url: "https://www.instagram.com/capt.pace/" }, { label: "Other CE Projects", url: "https://captlife.com/life/ace-projects/" }],
      [{ label: "ACE Migrants", url: "https://captlife.com/life/ace-projects/#:~:text=Next-,Migrants,-Through%20various%20engagements" }, { label: "Other CE Projects", url: "https://captlife.com/life/ace-projects/" }],
      [{ label: "Social Innovation", url: "https://captlife.com/csc/si/" }, { label: "Other CE Projects", url: "https://captlife.com/life/ace-projects/" }],
    ],
  },
];
